version: "3"

services:
  couchdb:
    build:
      context: ./couchdb-npmjs
      dockerfile: Dockerfile
    ports:
      - 5984:5984
    networks: 
      - backend
    volumes:
      - couchdb-data:/usr/local/var/lib/couchdb

networks:
  backend:

volumes:
  couchdb-data: